name: cplayer
description: "CPlayer - Play Music. Play Video."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  google_fonts: ^4.0.4
  cupertino_icons: ^1.0.5
  just_audio: ^0.9.37
  file_picker: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
